version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      
  pre_build:
    commands:
      - echo "Running pre-build function..."
      - python helloworld.py --stage pre_build

  build:
    commands:
      - echo "Starting the build process..."
      - # Your build commands go here, e.g., pytest or build scripts
      - echo "Build completed successfully."

  post_build:
    commands:
      - echo "Running post-build function..."
      - python helloworld.py --stage post_build
